batch_size: 16
classes: 3
encoder_name: resnet34
encoder_weights: imagenet
in_channels: 3
learning_rate: 0.0001
loss: combined
model_name: unet
num_epochs: 1000
optimizer: Adam
patch_size:
- 512
- 512
use_augmentation: true
weight_decay: 3.0e-05
